<?php
/**
 * Template for filter items block
 *
 * @var $block \SummaTheme\LayeredNavigation\Block\Navigation\FilterPriceRenderer
 */
?>
<div class="price-range-slider" data-role="<?= $block->getDataRole(); ?>">
    <div data-role="from-label"></div>
    <div data-role="to-label"></div>
    <div data-role="slider-bar"></div>
    <div class="actions-toolbar">
        <div data-role="message-box"></div>
        <div class="actions-primary">
            <a class="action primary small" data-role="apply-range">
                <span><?= __('OK'); ?></span>
            </a>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    { "[data-role=<?= $block->getDataRole(); ?>]" : { "rangeSlider" : <?= $block->getJsonConfig(); ?> } }
</script>
